# Generated by Django 3.1 on 2021-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacion', models.CharField(max_length=50)),
                ('instituto', models.CharField(max_length=100)),
                ('fecha_inicio', models.PositiveIntegerField()),
                ('fecha_final', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-fecha_final'],
            },
        ),
    ]
