# Generated by Django 3.1 on 2021-05-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Experience', '0003_auto_20210429_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencemodel',
            options={'ordering': ['-start_date']},
        ),
    ]
