# Generated by Django 3.1 on 2021-05-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Experience', '0004_auto_20210504_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencemodel',
            options={},
        ),
    ]
