# Generated by Django 3.1 on 2021-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsmodel',
            options={'ordering': ['-measure']},
        ),
    ]
