# Generated by Django 3.1 on 2021-04-29 13:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencemodel',
            options={},
        ),
        migrations.RenameField(
            model_name='experiencemodel',
            old_name='instituto',
            new_name='empleador',
        ),
        migrations.RemoveField(
            model_name='experiencemodel',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='experiencemodel',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='experiencemodel',
            name='formacion',
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='resumen',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
